# Generated by Django 4.2.13 on 2024-06-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("new_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exampledomainmodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
